In [1]:
### Plotting bettis

script_start_time = time()
println("\nimporting packages...")

using Pkg
using Statistics
using LinearAlgebra
using Eirene
using StatsBase
using CSV
using JLD
using DataFrames
using JSON
using MAT
using Plots

include("helper_functions.jl")
println("packages and functions imported")
printstyled("Elapsed time = $(time() - script_start_time) seconds \n \n", color = :yellow)

HTML{String}("<script>\n// Immediately-invoked-function-expression to avoid global variables.\n(function() {\n    var warning_div = document.getElementById(\"webio-warning-6598679953642285852\");\n    var hide = function () {\n        var script = document.getElementById(\"webio-setup-6571655983482893340\");\n        var parent = script && script.parentElement;\n        var grandparent = parent && parent.parentElement;\n        if (grandparent) {\n            grandparent.style.display = \"none\";\n        }\n        warning_div.style.display = \"none\";\n    };\n    if (typeof Jupyter !== \"undefined\") {\n        console.log(\"WebIO detected Jupyter notebook environment.\");\n        // Jupyter notebook.\n        var extensions = (\n            Jupyter\n            && Jupyter.notebook.config.data\n            && Jupyter.notebook.config.data.load_extensions\n        );\n        if (extensions && extensions[\"webio-jupyter-notebook\"]) {\n            // Extension already loaded.\n            console.log(\"Jupyter WebIO nbextension detected; not loading ad-hoc.\");\n            hide();\n            return;\n        }\n    } else if (window.location.pathname.includes(\"/lab\")) {\n        // Guessing JupyterLa\n        console.log(\"Jupyter Lab detected; make sure the @webio/jupyter-lab-provider labextension is installed.\");\n        hide();\n        return;\n    }\n})();\n\n</script>\n<p\n    id=\"webio-warning-6598679953642285852\"\n    class=\"output_text output_stderr\"\n    style=\"padding: 1em; font-weight: bold;\"\n>\n    Unable to load WebIO. Please make sure WebIO works for your Jupyter client.\n    For troubleshooting, please see <a href=\"https://juliagizmos.github.io/WebIO.jl/latest/providers/ijulia/\">\n    the WebIO/IJulia documentation</a>.\n    <!-- TODO: link to installation docs. -->\n</p>\n")


importing packages...


┌ Info: Recompiling stale cache file /opt/julia/compiled/v1.2/Plots/ld3vC.ji for Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]
└ @ Base loading.jl:1240


packages and functions imported
Elapsed time = 70.92116785049438 seconds 
 


In [2]:
### Set parameters

betti_colors = [["#243a4c"] ["#406372"] ["#66939e"] ["#9bc3c6"]]

# Read from config file
config_file = "config101220.json"
config = read_config("$(homedir())/configs/$(config_file)")

# Parameters for all graphs
const NNODES = config["NNODES"]
const MAXDIM = config["MAXDIM"]
const NREPS = config["NREPS"]
const DATE_STRING = config["DATE_STRING"]


### Locate data and find nametags
read_dir = "../processed_data/results/$(NNODES)nodes"
betti_files = filter(x->occursin("_bettis",x), readdir(read_dir))
betti_files = filter(x->occursin(DATE_STRING, x), betti_files)
betti_files = filter(x->!occursin("dsi", x), betti_files)

println("Located the following graph files:")
# for betti_file in betti_files
#     println(betti_file)
# end


# Locate the nametags
nametags = []
for betti_file in betti_files
    println(betti_file)
    tag = split(split(betti_file, "$(DATE_STRING)_")[2], "_bettis")[1]
    nametags = [nametags; tag]
end

nametags = unique(nametags)


for nametag in nametags
    namefiles = filter(x->occursin(nametag,x), betti_files)
    if length(namefiles)<12
    println(nametag)
    println(length(namefiles))
    end
end

nametags

Located the following graph files:
IID_70nodes_500reps_101220_thresh015_edge363_randomized_threshold_bettis.jld
IID_70nodes_500reps_101220_thresh015_edge363_threshold_bettis.jld
IID_70nodes_500reps_101220_thresh01_edge242_randomized_threshold_bettis.jld
IID_70nodes_500reps_101220_thresh01_edge242_threshold_bettis.jld
IID_70nodes_500reps_101220_thresh025_edge604_randomized_threshold_bettis.jld
IID_70nodes_500reps_101220_thresh025_edge604_threshold_bettis.jld
IID_70nodes_500reps_101220_thresh02_edge483_randomized_threshold_bettis.jld
IID_70nodes_500reps_101220_thresh02_edge483_threshold_bettis.jld
IID_70nodes_500reps_101220_thresh035_edge846_randomized_threshold_bettis.jld
IID_70nodes_500reps_101220_thresh035_edge846_threshold_bettis.jld
IID_70nodes_500reps_101220_thresh03_edge725_randomized_threshold_bettis.jld
IID_70nodes_500reps_101220_thresh03_edge725_threshold_bettis.jld
IID_70nodes_500reps_101220_thresh045_edge1087_randomized_threshold_bettis.jld
IID_70nodes_500reps_101220_thresh04

cosineGeometric_70nodes_500reps_3_101220_thresh065_edge1570_threshold_bettis.jld
cosineGeometric_70nodes_500reps_3_101220_thresh06_edge1449_randomized_threshold_bettis.jld
cosineGeometric_70nodes_500reps_3_101220_thresh06_edge1449_threshold_bettis.jld
cosineGeometric_70nodes_500reps_3_101220_thresh075_edge1812_randomized_threshold_bettis.jld
cosineGeometric_70nodes_500reps_3_101220_thresh075_edge1812_threshold_bettis.jld
cosineGeometric_70nodes_500reps_3_101220_thresh07_edge1691_randomized_threshold_bettis.jld
cosineGeometric_70nodes_500reps_3_101220_thresh07_edge1691_threshold_bettis.jld
cosineGeometric_70nodes_500reps_3_101220_thresh085_edge2053_randomized_threshold_bettis.jld
cosineGeometric_70nodes_500reps_3_101220_thresh085_edge2053_threshold_bettis.jld
cosineGeometric_70nodes_500reps_3_101220_thresh08_edge1932_randomized_threshold_bettis.jld
cosineGeometric_70nodes_500reps_3_101220_thresh08_edge1932_threshold_bettis.jld
cosineGeometric_70nodes_500reps_3_101220_thresh09_edge2174_r

geometricConf_70nodes_500reps_001_100_101220_thresh025_edge604_randomized_threshold_bettis.jld
geometricConf_70nodes_500reps_001_100_101220_thresh025_edge604_threshold_bettis.jld
geometricConf_70nodes_500reps_001_100_101220_thresh02_edge483_randomized_threshold_bettis.jld
geometricConf_70nodes_500reps_001_100_101220_thresh02_edge483_threshold_bettis.jld
geometricConf_70nodes_500reps_001_100_101220_thresh035_edge846_randomized_threshold_bettis.jld
geometricConf_70nodes_500reps_001_100_101220_thresh035_edge846_threshold_bettis.jld
geometricConf_70nodes_500reps_001_100_101220_thresh03_edge725_randomized_threshold_bettis.jld
geometricConf_70nodes_500reps_001_100_101220_thresh03_edge725_threshold_bettis.jld
geometricConf_70nodes_500reps_001_100_101220_thresh045_edge1087_randomized_threshold_bettis.jld
geometricConf_70nodes_500reps_001_100_101220_thresh045_edge1087_threshold_bettis.jld
geometricConf_70nodes_500reps_001_100_101220_thresh04_edge966_randomized_threshold_bettis.jld
geometricConf

rmsd_70nodes_500reps_3_101220_thresh085_edge2053_threshold_bettis.jld
rmsd_70nodes_500reps_3_101220_thresh08_edge1932_randomized_threshold_bettis.jld
rmsd_70nodes_500reps_3_101220_thresh08_edge1932_threshold_bettis.jld
rmsd_70nodes_500reps_3_101220_thresh09_edge2174_randomized_threshold_bettis.jld
rmsd_70nodes_500reps_3_101220_thresh09_edge2174_threshold_bettis.jld
sqdEuclidean_70nodes_500reps_3_101220_thresh015_edge363_randomized_threshold_bettis.jld
sqdEuclidean_70nodes_500reps_3_101220_thresh015_edge363_threshold_bettis.jld
sqdEuclidean_70nodes_500reps_3_101220_thresh01_edge242_randomized_threshold_bettis.jld
sqdEuclidean_70nodes_500reps_3_101220_thresh01_edge242_threshold_bettis.jld
sqdEuclidean_70nodes_500reps_3_101220_thresh025_edge604_randomized_threshold_bettis.jld
sqdEuclidean_70nodes_500reps_3_101220_thresh025_edge604_threshold_bettis.jld
sqdEuclidean_70nodes_500reps_3_101220_thresh02_edge483_randomized_threshold_bettis.jld
sqdEuclidean_70nodes_500reps_3_101220_thresh02_edge4

34-element Array{Any,1}:
 "thresh015_edge363_randomized_threshold" 
 "thresh015_edge363_threshold"            
 "thresh01_edge242_randomized_threshold"  
 "thresh01_edge242_threshold"             
 "thresh025_edge604_randomized_threshold" 
 "thresh025_edge604_threshold"            
 "thresh02_edge483_randomized_threshold"  
 "thresh02_edge483_threshold"             
 "thresh035_edge846_randomized_threshold" 
 "thresh035_edge846_threshold"            
 "thresh03_edge725_randomized_threshold"  
 "thresh03_edge725_threshold"             
 "thresh045_edge1087_randomized_threshold"
 ⋮                                        
 "thresh06_edge1449_randomized_threshold" 
 "thresh06_edge1449_threshold"            
 "thresh075_edge1812_randomized_threshold"
 "thresh075_edge1812_threshold"           
 "thresh07_edge1691_randomized_threshold" 
 "thresh07_edge1691_threshold"            
 "thresh085_edge2053_randomized_threshold"
 "thresh085_edge2053_threshold"           
 "thresh08_edge1932_randomize

In [3]:
## Filter to include JUST the threshold ones
thresh_files = filter(x -> occursin("threshold",x),betti_files)
thresh_files = filter(x -> !occursin("randomized",x),thresh_files)
thresh_files = filter(x -> !occursin("clique",x),thresh_files)
thresh_files = filter(x -> !occursin("Triangle",x),thresh_files)
thresh_files = filter(x -> !occursin("noise",x),thresh_files)

202-element Array{String,1}:
 "IID_70nodes_500reps_101220_thresh015_edge363_threshold_bettis.jld"            
 "IID_70nodes_500reps_101220_thresh01_edge242_threshold_bettis.jld"             
 "IID_70nodes_500reps_101220_thresh025_edge604_threshold_bettis.jld"            
 "IID_70nodes_500reps_101220_thresh02_edge483_threshold_bettis.jld"             
 "IID_70nodes_500reps_101220_thresh035_edge846_threshold_bettis.jld"            
 "IID_70nodes_500reps_101220_thresh03_edge725_threshold_bettis.jld"             
 "IID_70nodes_500reps_101220_thresh045_edge1087_threshold_bettis.jld"           
 "IID_70nodes_500reps_101220_thresh04_edge966_threshold_bettis.jld"             
 "IID_70nodes_500reps_101220_thresh055_edge1329_threshold_bettis.jld"           
 "IID_70nodes_500reps_101220_thresh05_edge1208_threshold_bettis.jld"            
 "IID_70nodes_500reps_101220_thresh065_edge1570_threshold_bettis.jld"           
 "IID_70nodes_500reps_101220_thresh06_edge1449_threshold_bettis.jld"            

In [4]:
## Filter to only include every kth data point - for faster visualization loading

model_names = []
for thresh_file in thresh_files
    name = split(thresh_file, "_")[1]
    model_names = [model_names; name]
end

unique!(model_names)
betti_names = ["IID","assortative","coreperiphery", "cosineGeometric","disassortative", "discreteUniform","dotProduct", "geometricConf", "randomGeometric", "ringLattice", "rmsd", "squaredEuclidean" ];


In [6]:
model_names = ["IID","assortative","coreperiphery", "cosineGeometric","disassortative", "discreteUniform",
    "dotProduct", "geometricConf", "randomGeometric", "ringLattice", "rmsd", "squaredEuclidean" ]
mat_dir = "../processed_data/classification/"
mat_files = readdir(mat_dir)
mat_files = filter(x -> occursin(".mat",x), mat_files)
mat1 = matread("$(mat_dir)/$(mat_files[1])")
mat_files

187-element Array{String,1}:
 "matrix_allNO_0.1.mat"    
 "matrix_allNO_0.15.mat"   
 "matrix_allNO_0.2.mat"    
 "matrix_allNO_0.25.mat"   
 "matrix_allNO_0.3.mat"    
 "matrix_allNO_0.35.mat"   
 "matrix_allNO_0.4.mat"    
 "matrix_allNO_0.45.mat"   
 "matrix_allNO_0.5.mat"    
 "matrix_allNO_0.55.mat"   
 "matrix_allNO_0.6.mat"    
 "matrix_allNO_0.65.mat"   
 "matrix_allNO_0.7.mat"    
 ⋮                         
 "matrix_prenoise_0.35.mat"
 "matrix_prenoise_0.4.mat" 
 "matrix_prenoise_0.45.mat"
 "matrix_prenoise_0.5.mat" 
 "matrix_prenoise_0.55.mat"
 "matrix_prenoise_0.6.mat" 
 "matrix_prenoise_0.65.mat"
 "matrix_prenoise_0.7.mat" 
 "matrix_prenoise_0.75.mat"
 "matrix_prenoise_0.8.mat" 
 "matrix_prenoise_0.85.mat"
 "matrix_prenoise_0.9.mat" 

In [7]:
mat_types = []
for mat_file in mat_files
    mat_types = [mat_types; split(mat_file,"_")[2]]
end
unique!(mat_types)

11-element Array{Any,1}:
 "allNO"        
 "allRand"      
 "all"          
 "bluesRand"    
 "blues"        
 "crossoverRand"
 "crossover"    
 "postnoiseRand"
 "postnoise"    
 "prenoiseRand" 
 "prenoise"     

In [8]:
## Colors
correct = "#03524C"
incorrect = "#531B56"


# Loop through mat files
mat_file_types = filter(x -> occursin(mat_types[1],x), mat_files)
println(mat_file_types)
# multiply all the off diagonal entries by -1 so that the diverging colormap works appropriately
thresholds = collect(0.1:0.05:0.9)

for mat_type in mat_types
    
    plot_array = Any[]
    
    for threshold in thresholds

        mat1 = matread("$(mat_dir)/matrix_$(mat_type)_$threshold.mat")

        factor = (-1).*ones(size(mat1["C"])) .+ (2 .*Matrix(I,size(mat1["C"])))

        if threshold==0.9


            p_i= heatmap(mat1["C"].*factor, c=cgrad([incorrect, :white, correct], [0,0.5, 1]),
                clim=(-250,250), yflip=true,
                xrotation=90,
                fontfamily=:Times, aspect_ratio=:equal, grid=false)
            xticks!(collect(1:12), model_names)
            yticks!(collect(1:12), model_names)

        else
            p_i= heatmap(mat1["C"].*factor, c=cgrad([incorrect, :white, correct], [0,0.5, 1]),
                clim=(-250,250), yflip=true,
                xrotation=90,
                fontfamily=:Times, aspect_ratio=:equal, axis=nothing, legend=nothing, border=:none)
            xticks!(collect(1:12), model_names)
            yticks!(collect(1:12), model_names)
            title!("rho_t = $(threshold)")
        end

        plot(p_i,size=(300,300))
        push!(plot_array,p_i)

    end

    l = @layout [a b c d; e f g h; i j k l; m n o p; q]
    plot(plot_array..., layout=l, size=(3000,4000))
    savefig("../Figures/confusion_matrices_$(mat_type)_all.pdf")
end

["matrix_allNO_0.1.mat", "matrix_allNO_0.15.mat", "matrix_allNO_0.2.mat", "matrix_allNO_0.25.mat", "matrix_allNO_0.3.mat", "matrix_allNO_0.35.mat", "matrix_allNO_0.4.mat", "matrix_allNO_0.45.mat", "matrix_allNO_0.5.mat", "matrix_allNO_0.55.mat", "matrix_allNO_0.6.mat", "matrix_allNO_0.65.mat", "matrix_allNO_0.7.mat", "matrix_allNO_0.75.mat", "matrix_allNO_0.8.mat", "matrix_allNO_0.85.mat", "matrix_allNO_0.9.mat"]


In [5]:
mat_files

17-element Array{String,1}:
 "matrix_all_0.1.mat" 
 "matrix_all_0.15.mat"
 "matrix_all_0.2.mat" 
 "matrix_all_0.25.mat"
 "matrix_all_0.3.mat" 
 "matrix_all_0.35.mat"
 "matrix_all_0.4.mat" 
 "matrix_all_0.45.mat"
 "matrix_all_0.5.mat" 
 "matrix_all_0.55.mat"
 "matrix_all_0.6.mat" 
 "matrix_all_0.65.mat"
 "matrix_all_0.7.mat" 
 "matrix_all_0.75.mat"
 "matrix_all_0.8.mat" 
 "matrix_all_0.85.mat"
 "matrix_all_0.9.mat" 